location:
  data_root_dir: /home/ubuntu/LamaInpainting/LamaInpainting/lama/medical_dataset
  out_root_dir: /home/ubuntu/LamaInpainting/LamaInpainting/lama/experiments
  tb_dir: /home/ubuntu/LamaInpainting/LamaInpainting/lama/tb_logs
  load_checkpoint_path: /home/ubuntu/LamaInpainting/LamaInpainting/lama/experiments/ubuntu_2024-06-29_19-27-07_train_big-lama_/models/epoch=0-step=999.ckpt
  trainer:
    kwargs:
      gpus: 1
      accelerator: ddp
data:
  batch_size: 10
  val_batch_size: 2
  num_workers: 3
  train:
    indir: /home/ubuntu/LamaInpainting/LamaInpainting/lama/medical_dataset/train
    out_size: 256
    mask_gen_kwargs:
      irregular_proba: 1
      irregular_kwargs:
        max_angle: 4
        max_len: 200
        max_width: 100
        max_times: 5
        min_times: 1
      box_proba: 1
      box_kwargs:
        margin: 10
        bbox_min_size: 30
        bbox_max_size: 150
        max_times: 4
        min_times: 1
      segm_proba: 0
    transform_variant: distortions
    dataloader_kwargs:
      batch_size: 10
      shuffle: true
      num_workers: 3
  val:
    indir: /home/ubuntu/LamaInpainting/LamaInpainting/lama/medical_dataset/val/random_thin_512
    img_suffix: .png
    dataloader_kwargs:
      batch_size: 2
      shuffle: false
      num_workers: 3
  visual_test:
    indir: /home/ubuntu/LamaInpainting/LamaInpainting/lama/medical_dataset/visual_test/random_thin_512
    img_suffix: .png
    pad_out_to_modulo: 32
    dataloader_kwargs:
      batch_size: 1
      shuffle: false
      num_workers: 3
discriminator:
  kind: pix2pixhd_nlayer
  input_nc: 3
  ndf: 64
  n_layers: 4
optimizers:
  generator:
    kind: adam
    lr: 0.001
  discriminator:
    kind: adam
    lr: 0.0001
visualizer:
  kind: directory
  outdir: /home/ubuntu/LamaInpainting/LamaInpainting/lama/experiments/ubuntu_2024-06-30_06-41-54_train_big-lama_/samples
  key_order:
  - image
  - predicted_image
  - discr_output_fake
  - discr_output_real
  - inpainted
  rescale_keys:
  - discr_output_fake
  - discr_output_real
evaluator:
  kind: default
  inpainted_key: inpainted
  integral_kind: ssim_fid100_f1
trainer:
  kwargs:
    gpus: -1
    accelerator: ddp
    max_epochs: 40
    gradient_clip_val: 1
    log_gpu_memory: None
    limit_train_batches: 25000
    val_check_interval: 25000
    log_every_n_steps: 250
    precision: 32
    terminate_on_nan: false
    check_val_every_n_epoch: 1
    num_sanity_val_steps: 8
    replace_sampler_ddp: false
  checkpoint_kwargs:
    verbose: true
    save_top_k: 5
    save_last: true
    period: 1
    monitor: val_ssim_fid100_f1_total_mean
    mode: max
run_title: ''
training_model:
  kind: default
  visualize_each_iters: 1000
  concat_mask: true
  store_discr_outputs_for_vis: true
losses:
  l1:
    weight_missing: 0
    weight_known: 10
  perceptual:
    weight: 0
  adversarial:
    kind: r1
    weight: 10
    gp_coef: 0.001
    mask_as_fake_target: true
    allow_scale_mask: true
  feature_matching:
    weight: 100
  resnet_pl:
    weight: 30
    weights_path: /home/ubuntu/LamaInpainting/LamaInpainting/lama
generator:
  kind: ffc_resnet
  input_nc: 4
  output_nc: 3
  ngf: 64
  n_downsampling: 3
  n_blocks: 18
  add_out_act: sigmoid
  init_conv_kwargs:
    ratio_gin: 0
    ratio_gout: 0
    enable_lfu: false
  downsample_conv_kwargs:
    ratio_gin: 0
    ratio_gout: 0
    enable_lfu: false
  resnet_conv_kwargs:
    ratio_gin: 0.75
    ratio_gout: 0.75
    enable_lfu: false
