model_dir: C:\Users\Administrator\Projects\FORF\lama\models\fine-tuned2-big-lama
config_path: C:\Users\Administrator\Projects\FORF\lama\models\fine-tuned2-big-lama\config.yaml
checkpoint: fine-tuned2-epoch13.ckpt